# infra/docker/docker-compose.yml

services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ../../apps/frontend
    ports:
      - '3000:3000'
    depends_on:
      - api-gateway
      - llm-service
    env_file:
      - ./.env
    environment:
      - REACT_APP_API_URL=http://api-gateway:3001

  api-gateway:
    build:
      context: ../../apps/api-gateway
    ports:
      - '3001:3001'
    depends_on:
      - llm-service
      - postgres
    env_file:
      - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  llm-service:
    build:
      context: ../../apps/llm-service
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - ollama

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama

volumes:
  ollama_data:
  postgres_data:
