# Docker Compose Configuration for AI Support Chat Application
# Complete the missing parts as indicated by TODO comments

version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:16
    # TODO: Configure port mapping (5432:5432)
    
    # TODO: Configure environment variables using the .env file
    
    # TODO: Set up volume for data persistence
    
  # Frontend Service (React application)
  frontend:
    build:
      context: ../../apps/frontend
    ports:
      - '3000:3000'
    depends_on:
      - api-gateway
    environment:
      - REACT_APP_API_URL=http://api-gateway:3001

  # API Gateway Service (Express server)
  api-gateway:
    build:
      context: ../../apps/api-gateway
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - llm-service
    # TODO: Configure environment variables for database connection
    
  # LLM Service (Interfaces with Ollama)
  llm-service:
    build:
      context: ../../apps/llm-service
    # TODO: Configure port mapping 
    
    depends_on:
      - ollama
    # TODO: Configure environment variables for Ollama connection
    
  # Ollama Service (Runs the LLM)
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - '11434:11434'
    # TODO: Configure volume for model persistence
    
    container_name: ollama

# TODO: Define volumes for data persistence
volumes:
  # Define volume for PostgreSQL data
  
  # Define volume for Ollama models
